@startuml
'https://plantuml.com/class-diagram

abstract Piece
class Tetromino
abstract Block
class Point
class GameBoard
class Tetris
class Grid

Piece <|-- Tetromino
Tetromino <|---- OTetromino
Tetromino <|-- ITetromino
Tetromino <|---- LTetromino
Tetromino <|-- JTetromino
Tetromino <|---- TTetromino
Tetromino <|-- ZTetromino
Tetromino <|---- STetromino

Block -- Point
Tetris *-- GameBoard
GameBoard *-- Playfield
Playfield *-- Grid

class Grid {
    blocks: List<Block>
    getFilledRows(): List<Block>
    removeRow(row:int)
    addBlocks(blocks:List<Block>)
}

abstract Board {
    Block[20][10]
}

abstract Piece {
    Optional<Block>[][]
    pivot: Point
    positions: Point[][]
}

class Point {
    row: int
    column: int
}

abstract Block {
    position: Point
    width: int
    height: int
    color: Color

    setPositon(Point)
}

@enduml